messages:
  noItemInHand: "你手中没有物品可以附魔！"
  invalidEnchantment: "无效的附魔"
  failedToEnchant_getMeta: "无法获取物品元数据！"
  failedToEnchant_errorLevel: "附魔等级错误，正确等级应为"
  clearEnchantment: "已清除附魔"
  successEnchant: "物品已成功附魔"

update_available1: "发现新版本: "
update_available2: "，请前往 https://github.com/Findoutsider/EasyEnchant 查看"
update_info: "新版本信息: "
current_version: "当前已是最新版本: v"
update_error: "获取新版本失败: "
update_exception: "获取新版本时发生异常: "
